[package]
name = "rmk-pg1kb-proto-ph3"
version = "0.1.0"
authors = ["vwbugowner1976"]
description = "RMK firmware for PG1KB Proto PH3 with PAW3222 trackballs"
repository = "https://github.com/vwbugowner1976/rmk-pg1kb-proto-ph3"
readme = "README.md"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
rmk = { version = "0.9", default-features = false, features = [
    "storage",
    "watchdog",
    "nrf52840_ble",
    "split",
    "async_matrix",
    "adafruit_bl",
    "usb_log",
] }
nrf-sdc = { version = "0.4.0", features = [
    "defmt",
    "peripheral",
    "central",
    "nrf52840",
] }
nrf-mpsl = { version = "0.4.0", features = [
    "defmt",
    "critical-section-impl",
    "nrf52840",
] }
bt-hci = { version = "0.10", features = ["defmt"] }

cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
usbd-hid = "0.10"
embassy-time = { version = "0.5", features = ["tick-hz-32_768", "defmt", "defmt-timestamp-uptime"] }
embassy-nrf = { version = "0.11", features = [
    "defmt",
    "nrf52840",
    "time-driver-rtc1",
    "gpiote",
    "unstable-pac",
    "nfc-pins-as-gpio",
    "time",
] }
embassy-executor = { version = "0.10", features = [
    "defmt",
    "platform-cortex-m",
    "executor-thread",
] }
log = "0.4.29"
defmt = "1"
defmt-rtt = "1"
panic-probe = { version = "1", features = ["print-defmt"] }
static_cell = "2"

[[bin]]
name = "central"
path = "src/central.rs"

[[bin]]
name = "peripheral"
path = "src/peripheral.rs"

[profile.dev]
codegen-units = 1
debug = true
opt-level = 1
overflow-checks = true
lto = false
panic = "unwind"

[profile.release]
codegen-units = 1
debug = true
opt-level = "z"
overflow-checks = false
lto = "fat"
