[tasks.install-llvm-tools]
install_crate = { rustup_component_name = "llvm-tools" }

[tasks.flip-link]
install_crate = { crate_name = "flip-link", binary = "flip-link", test_arg = ["-h"] }

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.objcopy-central]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = ["objcopy", "--help"] }
command = "cargo"
args = ["objcopy", "--release", "--bin", "central", "--", "-O", "ihex", "rmk-pg1kb-proto-ph3-central.hex"]
dependencies = ["build"]

[tasks.objcopy-peripheral]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = ["objcopy", "--help"] }
command = "cargo"
args = ["objcopy", "--release", "--bin", "peripheral", "--", "-O", "ihex", "rmk-pg1kb-proto-ph3-peripheral.hex"]
dependencies = ["build"]

[tasks.uf2-central]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = ["hex-to-uf2", "--help"] }
command = "cargo"
args = ["hex-to-uf2", "--input-path", "rmk-pg1kb-proto-ph3-central.hex", "--output-path", "rmk-pg1kb-proto-ph3-central.uf2", "--family", "nrf52840"]
dependencies = ["objcopy-central"]

[tasks.uf2-central-v2]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = ["hex-to-uf2", "--help"] }
command = "cargo"
args = ["hex-to-uf2", "--input-path", "rmk-pg1kb-proto-ph3-central.hex", "--output-path", "rmk-pg1kb-proto-ph3-central-v2.uf2", "--family", "nrf52840"]
dependencies = ["objcopy-central"]

[tasks.uf2-central-v4]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = ["hex-to-uf2", "--help"] }
command = "cargo"
args = ["hex-to-uf2", "--input-path", "rmk-pg1kb-proto-ph3-central.hex", "--output-path", "rmk-pg1kb-proto-ph3-central-v4.uf2", "--family", "nrf52840"]
dependencies = ["objcopy-central"]

[tasks.uf2-central-v5]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = ["hex-to-uf2", "--help"] }
command = "cargo"
args = ["hex-to-uf2", "--input-path", "rmk-pg1kb-proto-ph3-central.hex", "--output-path", "rmk-pg1kb-proto-ph3-central-v5.uf2", "--family", "nrf52840"]
dependencies = ["objcopy-central"]

[tasks.uf2-central-v6]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = ["hex-to-uf2", "--help"] }
command = "cargo"
args = ["hex-to-uf2", "--input-path", "rmk-pg1kb-proto-ph3-central.hex", "--output-path", "rmk-pg1kb-proto-ph3-central-v6.uf2", "--family", "nrf52840"]
dependencies = ["objcopy-central"]

[tasks.uf2-central-v7]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = ["hex-to-uf2", "--help"] }
command = "cargo"
args = ["hex-to-uf2", "--input-path", "rmk-pg1kb-proto-ph3-central.hex", "--output-path", "rmk-pg1kb-proto-ph3-central-v7.uf2", "--family", "nrf52840"]
dependencies = ["objcopy-central"]

[tasks.uf2-peripheral]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = ["hex-to-uf2", "--help"] }
command = "cargo"
args = ["hex-to-uf2", "--input-path", "rmk-pg1kb-proto-ph3-peripheral.hex", "--output-path", "rmk-pg1kb-proto-ph3-peripheral.uf2", "--family", "nrf52840"]
dependencies = ["objcopy-peripheral"]

[tasks.uf2-peripheral-v5]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = ["hex-to-uf2", "--help"] }
command = "cargo"
args = ["hex-to-uf2", "--input-path", "rmk-pg1kb-proto-ph3-peripheral.hex", "--output-path", "rmk-pg1kb-proto-ph3-peripheral-v5.uf2", "--family", "nrf52840"]
dependencies = ["objcopy-peripheral"]

[tasks.uf2-peripheral-v6]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = ["hex-to-uf2", "--help"] }
command = "cargo"
args = ["hex-to-uf2", "--input-path", "rmk-pg1kb-proto-ph3-peripheral.hex", "--output-path", "rmk-pg1kb-proto-ph3-peripheral-v6.uf2", "--family", "nrf52840"]
dependencies = ["objcopy-peripheral"]

[tasks.uf2-peripheral-v7]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = ["hex-to-uf2", "--help"] }
command = "cargo"
args = ["hex-to-uf2", "--input-path", "rmk-pg1kb-proto-ph3-peripheral.hex", "--output-path", "rmk-pg1kb-proto-ph3-peripheral-v7.uf2", "--family", "nrf52840"]
dependencies = ["objcopy-peripheral"]

[tasks.uf2-v5]
dependencies = ["uf2-central-v5", "uf2-peripheral-v5"]

[tasks.uf2-v6]
dependencies = ["uf2-central-v6", "uf2-peripheral-v6"]

[tasks.uf2-v7]
dependencies = ["uf2-central-v7", "uf2-peripheral-v7"]

[tasks.uf2]
dependencies = ["uf2-central", "uf2-peripheral"]
